### ISSUE TITLE
Multiple cp number

### ISSUE THREAD

**Issue by JGMAGNO** [layadcircuits/Saleng-GSM#3]
Hello I just want to ask if receving multiple cp numbers are possible with saleng gsm?

**Comment by cdmalecdan** [comment]
For hardware concerns, please approach your hardware supplier. 
If you are asking if this library can receive from multiple senders, then yes.

**Comment by JGMAGNO** [comment]
Hello good morning, Can I contribute to this project? Like another examples using Saleng-GSM library. :)

**Comment by cdmalecdan** [comment]
Sure, have a pull request and we will integrate accordingly
